package DAO;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import Model.Account;
import Util.ConnectionUtil;

/**
 * This is a Data Access Object that manages the interactions Java objects of
 * the class "Account" and the SQL database table "account".
 * 
 * The database table "account" has the columns:
 * account_id   int             Primary key, and unique identifers for accounts
 * username     varchar(255)    Name for account, is unique
 * password     varchar(255)    Login for account
 */
public class AccountDAO {
    /**
     * This registers/inserts a new account into the "account" database table.
     * 
     * "account_id" should be automatically generated by the database because
     * it's auto-incremented.
     * 
     * @param account   The new account to be registered
     * 
     * @return  The successfully registered account, or "null" if registration
     *          failed
     */
    public Account registerAccount(Account account) {
        Connection connection = ConnectionUtil.getConnection();
        try {
            // Make SQL statement and execute it
            String sql = "INSERT INTO account (username, password) VALUES (?, ?)";
            PreparedStatement ps = connection.prepareStatement(sql);

            ps.setString(1, account.getUsername());
            ps.setString(2, account.getPassword());

            ps.executeUpdate();


            // Get primary key generated by database and add it to account
            ResultSet pkeyResultSet = ps.getGeneratedKeys();

            if(pkeyResultSet.next()) {
                int generated_account_id = (int) pkeyResultSet.getLong(1);

                // Return successfully registered account
                return new Account( generated_account_id,
                                    account.getUsername(),
                                    account.getPassword());
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        return null;    // Occurs if registration failed
    }
}
